-- 상품코드 별 매출액(판매가 * 판매량) 
SELECT A.PRODUCT_CODE, sum(SALES_AMOUNT) * A.PRICE as SALES
FROM PRODUCT AS A
INNER JOIN OFFLINE_SALE AS B
                        ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES DESC , PRODUCT_CODE ASC