-- 코드를 입력하세요
# SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE,'%Y-%d-%m') as PUBLISHED_DATE
# FROM BOOK AS A
#           INNER JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
# WHERE A.CATEGORY = '경제'
# ORDER BY PUBLISHED_DATE ASC


-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK INNER JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE CATEGORY = '경제' ORDER BY PUBLISHED_DATE;